"""Initial migration3

Revision ID: 081bf37c0377
Revises: f41432a531cc
Create Date: 2024-03-14 22:03:00.500870

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '081bf37c0377'
down_revision = 'f41432a531cc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('caca',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=80),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=80),
               nullable=False)
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('caca',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)

    # ### end Alembic commands ###
