"""Initial migration2

Revision ID: f0231c55a122
Revises: 
Create Date: 2024-03-22 15:36:48.857901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f0231c55a122'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=1024), nullable=True),
    sa.Column('creationDate', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=1024), nullable=True),
    sa.Column('password', sa.String(length=1024), nullable=True),
    sa.Column('avatar', sa.String(length=1024), nullable=True),
    sa.Column('email', sa.String(length=512), nullable=True),
    sa.Column('dateOfBirth', sa.DateTime(timezone=True), nullable=True),
    sa.Column('creationDate', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('userTypeId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['userTypeId'], ['user_type.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('exercise_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=1024), nullable=True),
    sa.Column('creationDate', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('routine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=1024), nullable=True),
    sa.Column('creationDate', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exercise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=1024), nullable=True),
    sa.Column('creationDate', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('userId', sa.Integer(), nullable=True),
    sa.Column('exerciseTypeId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exerciseTypeId'], ['exercise_type.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('execution_exercise',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creationDate', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('exerciseId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['exerciseId'], ['exercise.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('exercise_routine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('creationDate', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('routineId', sa.Integer(), nullable=True),
    sa.Column('excerciseId', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['excerciseId'], ['exercise.id'], ),
    sa.ForeignKeyConstraint(['routineId'], ['routine.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exercise_routine')
    op.drop_table('execution_exercise')
    op.drop_table('exercise')
    op.drop_table('routine')
    op.drop_table('exercise_type')
    op.drop_table('user')
    op.drop_table('user_type')
    # ### end Alembic commands ###
